import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import GlobalProvider from "@/providers/GlobalProvider";
import "@/styles/globals.css";

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Your Clock Onoine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={"clock-astatic-theme"}>
      <body className={`${grotesk.className} antialiased`}>
        <GlobalProvider>
          <main className="flex h-full min-h-dvh flex-col">{children}</main>
        </GlobalProvider>
      </body>
    </html>
  );
}
