import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import GlobalProvider from "@/providers/GlobalProvider";
import "@/styles/globals.css";

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={"clock-astatic-theme"}>
      <body className={`${grotesk.className} antialiased`}>
        <main className="bg-background text-foreground h-full min-h-svh">
          <GlobalProvider>{children}</GlobalProvider>
        </main>
      </body>
    </html>
  );
}
